// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSbC0zPyM5nnsbY-Ui71bw46ygbu0d2Fs',
    appId: '1:584445569008:web:f53a9939f1cf4fbc0b9f35',
    messagingSenderId: '584445569008',
    projectId: 'microfinance-1ae96',
    authDomain: 'microfinance-1ae96.firebaseapp.com',
    databaseURL: 'https://microfinance-1ae96-default-rtdb.firebaseio.com',
    storageBucket: 'microfinance-1ae96.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_swg4YzaohOEoZHWWWPzhI2hCCG6BtlA',
    appId: '1:584445569008:android:b1320a68f4b8c6640b9f35',
    messagingSenderId: '584445569008',
    projectId: 'microfinance-1ae96',
    databaseURL: 'https://microfinance-1ae96-default-rtdb.firebaseio.com',
    storageBucket: 'microfinance-1ae96.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkKSTgd6cK4HhrF2CGrWpTxEMhNe7KhDU',
    appId: '1:584445569008:ios:c5b4c7f8e61a6cba0b9f35',
    messagingSenderId: '584445569008',
    projectId: 'microfinance-1ae96',
    databaseURL: 'https://microfinance-1ae96-default-rtdb.firebaseio.com',
    storageBucket: 'microfinance-1ae96.appspot.com',
    iosBundleId: 'com.example.microfinance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkKSTgd6cK4HhrF2CGrWpTxEMhNe7KhDU',
    appId: '1:584445569008:ios:2dffa9ec48dc20b00b9f35',
    messagingSenderId: '584445569008',
    projectId: 'microfinance-1ae96',
    databaseURL: 'https://microfinance-1ae96-default-rtdb.firebaseio.com',
    storageBucket: 'microfinance-1ae96.appspot.com',
    iosBundleId: 'com.example.microfinance.RunnerTests',
  );
}
